### PR TITLE
Update function getNewManyManyPks

### PR DESCRIPTION
**Pull request by Charopleot**
behavior was not working when using 'unselectValue' in dropDownList
(https://github.com/yiisoft/yii/blob/1.1.14/framework/web/helpers/CHtml.php#L933)

### CODE REVIEW

**Comment by cebe** [comment]
This does not make any sense to me, if it is a MANY_MANY relation it should be possible to add more than one user...

**Comment by Charopleot** [comment]
```php
array('multiple' => 'multiple', 'unselectValue' => '',)
```
and this is possible because "multiple". the problem is that "unselectValue" can not be an empty array and your behavior does not erase the relation values.

**Comment by cebe** [comment]
Why do you need the unselect value at all?

**Comment by Charopleot** [comment]
A website where I noticed it is done(corrected behavior and all is well))). But decided to write because for the dropdown list and yii (through fix "unselectValue") can remove all values (not my personal case, but in general) and it is expected that it will remain so (no value) after save, and this your ARbehavior missed ...
I only suggested solution to this. If I proposed behavior which disrupts work or wrong, I beg to explain why.

If you remove the previously selected option and save so it should be saved. IMHO :smile:

**Pull request closed without merging**
